# Generated by Django 6.0 on 2025-12-04 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profesionales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_hora", models.DateTimeField(verbose_name="Fecha y Hora")),
                (
                    "duracion_minutos",
                    models.IntegerField(default=30, verbose_name="Duración (minutos)"),
                ),
                (
                    "motivo_consulta",
                    models.TextField(verbose_name="Motivo de Consulta"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("AGENDADA", "Agendada"),
                            ("CONFIRMADA", "Confirmada"),
                            ("EN_CURSO", "En Curso"),
                            ("COMPLETADA", "Completada"),
                            ("CANCELADA", "Cancelada"),
                            ("NO_ASISTIO", "No Asistió"),
                        ],
                        default="AGENDADA",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "confirmada_por_paciente",
                    models.BooleanField(
                        default=False, verbose_name="Confirmada por Paciente"
                    ),
                ),
                (
                    "fecha_confirmacion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Confirmación"
                    ),
                ),
                (
                    "recordatorio_enviado",
                    models.BooleanField(
                        default=False, verbose_name="Recordatorio Enviado"
                    ),
                ),
                (
                    "fecha_recordatorio",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Recordatorio"
                    ),
                ),
                (
                    "fecha_cancelacion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Cancelación"
                    ),
                ),
                (
                    "motivo_cancelacion",
                    models.TextField(blank=True, verbose_name="Motivo de Cancelación"),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "notas_profesional",
                    models.TextField(blank=True, verbose_name="Notas del Profesional"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "cancelada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="citas_canceladas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cancelada Por",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        limit_choices_to={"rol": "PACIENTE"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profesional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citas",
                        to="profesionales.profesional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cita",
                "verbose_name_plural": "Citas",
                "ordering": ["-fecha_hora"],
                "unique_together": {("profesional", "fecha_hora")},
            },
        ),
        migrations.CreateModel(
            name="HistorialCita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado_anterior",
                    models.CharField(max_length=20, verbose_name="Estado Anterior"),
                ),
                (
                    "estado_nuevo",
                    models.CharField(max_length=20, verbose_name="Estado Nuevo"),
                ),
                (
                    "fecha_cambio",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Cambio"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "cita",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="citas.cita",
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modificado Por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Cita",
                "verbose_name_plural": "Historiales de Citas",
                "ordering": ["-fecha_cambio"],
            },
        ),
    ]
