# Generated by Django 6.0 on 2025-12-04 01:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "rut",
                    models.CharField(max_length=12, unique=True, verbose_name="RUT"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Correo Electrónico"
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                ("apellido", models.CharField(max_length=100, verbose_name="Apellido")),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Nacimiento"
                    ),
                ),
                (
                    "direccion",
                    models.TextField(blank=True, null=True, verbose_name="Dirección"),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("PACIENTE", "Paciente"),
                            ("PROFESIONAL", "Profesional"),
                            ("ADMIN", "Administrador"),
                        ],
                        default="PACIENTE",
                        max_length=20,
                        verbose_name="Rol",
                    ),
                ),
                (
                    "contador_inasistencias",
                    models.IntegerField(
                        default=0, verbose_name="Contador de Inasistencias"
                    ),
                ),
                (
                    "bloqueado",
                    models.BooleanField(default=False, verbose_name="¿Está Bloqueado?"),
                ),
                (
                    "fecha_bloqueo",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Bloqueo"
                    ),
                ),
                (
                    "motivo_bloqueo",
                    models.TextField(blank=True, verbose_name="Motivo del Bloqueo"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="Es Staff"),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Registro",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="HistorialBloqueo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_bloqueo",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Bloqueo"
                    ),
                ),
                (
                    "fecha_desbloqueo",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Desbloqueo"
                    ),
                ),
                ("motivo", models.TextField(verbose_name="Motivo")),
                (
                    "inasistencias_acumuladas",
                    models.IntegerField(verbose_name="Inasistencias Acumuladas"),
                ),
                (
                    "desbloqueado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bloqueos_gestionados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Desbloqueado Por",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_bloqueos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Bloqueo",
                "verbose_name_plural": "Historiales de Bloqueos",
                "ordering": ["-fecha_bloqueo"],
            },
        ),
    ]
