# Generated by Django 6.0 on 2025-12-04 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profesional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "especialidad",
                    models.CharField(max_length=100, verbose_name="Especialidad"),
                ),
                (
                    "registro_profesional",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        verbose_name="N° Registro Profesional",
                    ),
                ),
                (
                    "anos_experiencia",
                    models.IntegerField(verbose_name="Años de Experiencia"),
                ),
                (
                    "titulo_profesional",
                    models.CharField(max_length=150, verbose_name="Título Profesional"),
                ),
                (
                    "activo_para_citas",
                    models.BooleanField(default=True, verbose_name="Activo para Citas"),
                ),
                (
                    "duracion_cita_minutos",
                    models.IntegerField(
                        default=30, verbose_name="Duración de Cita (min)"
                    ),
                ),
                ("biografia", models.TextField(blank=True, verbose_name="Biografía")),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profesionales/",
                        verbose_name="Foto",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        limit_choices_to={"rol": "PROFESIONAL"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_profesional",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profesional",
                "verbose_name_plural": "Profesionales",
                "ordering": ["usuario__nombre"],
            },
        ),
        migrations.CreateModel(
            name="BloqueoHorario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateTimeField(verbose_name="Fecha y Hora de Inicio"),
                ),
                ("fecha_fin", models.DateTimeField(verbose_name="Fecha y Hora de Fin")),
                (
                    "motivo",
                    models.CharField(
                        choices=[
                            ("VACACIONES", "Vacaciones"),
                            ("PERMISO", "Permiso Médico"),
                            ("CAPACITACION", "Capacitación"),
                            ("ADMINISTRATIVO", "Tarea Administrativa"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Motivo",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado Por",
                    ),
                ),
                (
                    "profesional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bloqueos",
                        to="profesionales.profesional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bloqueo de Horario",
                "verbose_name_plural": "Bloqueos de Horarios",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="DisponibilidadProfesional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.IntegerField(
                        choices=[
                            (0, "Lunes"),
                            (1, "Martes"),
                            (2, "Miércoles"),
                            (3, "Jueves"),
                            (4, "Viernes"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ],
                        verbose_name="Día de la Semana",
                    ),
                ),
                ("hora_inicio", models.TimeField(verbose_name="Hora de Inicio")),
                ("hora_fin", models.TimeField(verbose_name="Hora de Fin")),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "profesional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disponibilidad",
                        to="profesionales.profesional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disponibilidad",
                "verbose_name_plural": "Disponibilidades",
                "ordering": ["dia_semana", "hora_inicio"],
                "unique_together": {("profesional", "dia_semana", "hora_inicio")},
            },
        ),
    ]
